### ISSUE TITLE
Some tests fail sporadically when building on Debian 

### ISSUE THREAD

**Issue by hillu** [golang/leveldb#25]
Debian bug [799472](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799472) describes that leveldb can't be built reliably from source due to failing tests. I have been able to reproduce the following test failures:
## 

```
--- FAIL: TestCompaction (0.02s)
        compaction_test.go:647: "+E": ldb: got "Aa.BC.Bb.Dad.", want "ABCDbd.".
```
## 

```
--- FAIL: TestTableCacheEvictions (0.04s)
        table_cache_test.go:77: numStillOpen is 101, want <= 100
```
## 

```
--- FAIL: TestTableCacheRandomAccessConcurrent (0.05s)
        table_cache_test.go:70: i=176: table closed too many or too few times: opened 5 times, closed 3 times
```

**Comment by satta** [comment]
Just curious if there is any progress on this?

**Comment by nigeltao** [comment]
I wasn't able to reproduce the flaky failures, but I made an educated guess to fix the three failures in the OP.

(The OP also links to a debian bug where TestLock fails, but that confuses me, as that test shouldn't be flaky at all. If a child process can lock an already locked file, that's a real problem.)

Anyway, does it look better on your end?

Sorry for the long delay in replying.

**Comment by hillu** [comment]
I still was able to reproduce at least the `TestCompaction` error with 0e15329 on pretty much the same sbuild setup that I used in January. I have started repeated builds of cbf1977 on the same setup and so far, things are looking good. We may get the package (and stenographer for which I had originally packaged it) into Debian before the stretch release, after all.

**Comment by satta** [comment]
I also ran test loops since this morning and didn't get a test failure so far. While it's difficult to prove that non-deterministic issues like this are fixed, I think this issue can be closed.
